### ISSUE TITLE
MVPリリースレビュー

### ISSUE THREAD

**Issue by kenchasonakai** [kyohei328/PhotoSpace#124]
MVPリリースお疲れ様でした！
以下にレビュー内容を記載します
こちらのissueのコメントに本リリースまでのスケジュールの返答をお願いいたします 🙇 

## SNSシェアについて
他の人の写真の詳細画面でSNSシェアボタンを押すと`写真を投稿しました`になってしまっており、自分で投稿していないのに自分で投稿したような文言になってしまっているので修正した方が良いかなと思いました。
[![Image from Gyazo](https://t.gyazo.com/teams/startup-technology/69ceab6f7e6c9b8890b0c758c9ceda68.gif)](https://startup-technology.gyazo.com/69ceab6f7e6c9b8890b0c758c9ceda68)

## 画像投稿について
画像を投稿した際Topページに飛ばされるだけで何が起きたのかがわからないのでフラッシュメッセージなどで正常に投稿出来たことを伝えたり、画面遷移する先を工夫するとユーザーに違和感なく使ってもらえるかなと思いました。
[![Image from Gyazo](https://t.gyazo.com/teams/startup-technology/a2b7de1c45a884bafc4466185fc80cda.gif)](https://startup-technology.gyazo.com/a2b7de1c45a884bafc4466185fc80cda)

## コンソールについて
console.logが残ってしまっているのかコンソールにログが出てしまっているので消しましょう
[![Image from Gyazo](https://t.gyazo.com/teams/startup-technology/a5db21cb3b05f39b9366199efaa5fad6.jpg)](https://startup-technology.gyazo.com/a5db21cb3b05f39b9366199efaa5fad6)

## Lintについて
必要ないコメントは削除すると良いかと思います
https://github.com/kyohei328/PhotoSpace/blob/444d0da34e201d54eee97d28254ce588feb52f16/app/controllers/api/v1/contest_entries_controller.rb#L12
https://github.com/kyohei328/PhotoSpace/blob/main/app/controllers/api/v1/contest_results_controller.rb
合わせてrubocopなどのLintチェックツールを導入すると良いと思います

## その他
一番始めに見られる部分なので、就活までにREADMEを整理しておきましょう

**Comment by kyohei328** [comment]
レビューありがとうございます！

## 画像投稿について
投稿完了のフラッシュメッセージを表示するように修正したいと思います。

## 本リリースまでのスケジュール
2/16を本リリース予定としたいと考えています。
スケジュールの内訳は下記です。

- コメント機能（4日）
  - 投稿された写真にコメントが投稿できること
  - 写真詳細ページに投稿されたコメントが表示されること
  - 投稿したコメントを削除できること
- タグ機能（4日）
  - 写真を投稿するときにタグ付けできること
  - 投稿したタグを編集できること
  - 投稿したタグを削除できること
- カテゴリー機能（4日）
  - 写真を投稿するときにカテゴリーを付けられること
  - 写真に付いたカテゴリーを変更できること
- タグ検索機能（3日）
  - タグで検索できること
- カテゴリー検索機能（3日）
  - カテゴリーで検索できること
- 写真添削機能（1週間）
  - 他のユーザーに添削依頼(メッセージ)を送れること
  - 他のユーザーとチャットで会話できること
- 写真の詳細編集機能（3日）
  -  撮影機材の変更ができる
  - 写真カテゴリーが変更できる
  - 撮影シーンが変更できる
  - ISO感度を変更できる
  - 露光補正値を変更できる
  - 焦点距離を変更できる
  - 撮影モードを変更できる
  - シャッタースピードを変更できる
  - 絞り値を変更できる
  - ホワイトバランスを変更できる
  - イメージサイズを変更できる
  - 撮影地を変更できる
- 写真投稿後の挙動修正（4H）
  - 写真投稿後に投稿が完了したメッセージを表示
- コンソール修正（2H）
  - コンソールに表示されているログを表示しないようにする
- Lintの修正（2H）
  - 不要なコメントアウトを削除
